[package]
name = "d01p1"
version = "0.1.0"
authors = ["Marcel MÃ¼ller <neikos@neikos.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
